# Generated by Django 3.1.1 on 2020-09-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('loan_amount', models.CharField(choices=[('tn', 'N10,000'), ('tw', 'N20,000'), ('th', 'N30,000'), ('fo', 'N40,000'), ('fi', 'N50,000'), ('si', 'N60,000'), ('se', 'N70,000'), ('ei', 'N80,000'), ('ni', 'N90,000'), ('hu', 'N100,000'), ('th', 'N200,000'), ('rh', 'N300,000'), ('fh', 'N400,000'), ('vh', 'N500,000'), ('sh', 'N600,000'), ('vh', 'N700,000'), ('eh', 'N800,000'), ('nh', 'N900,000'), ('1h', 'N1,000,000')], max_length=2)),
                ('bvn', models.PositiveIntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
