# Generated by Django 3.1.1 on 2020-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank',
            field=models.CharField(default='GT Bank', max_length=100),
            preserve_default=False,
        ),
    ]
