# Generated by Django 3.1.1 on 2020-09-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
