# Generated by Django 3.1.1 on 2020-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bvn',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
